### ISSUE TITLE
Question on the BUILD file.

### ISSUE THREAD

**Issue by timothymarois** [aurium/simland#2]
How would you execute the Build file? 

Also, this uses node? I'd like to contribute to this and see what I can come up with, just trying to get it workin locally or on my server. 

Thanks

**Comment by aurium** [comment]
Hi Timothy,

The build is only a packager to join the modularized code. That was done fast for js13k and must add a minifier like uglifier. You must run in a console on the project root, but that uses UNIX path, so may not works on windows.

This game was done to run in browser with the generated static files. I use node only for the builder. You can run it from your machine, without HTTP server. :-)
